# Generated by Django 4.2.16 on 2024-11-07 13:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя клиента")),
                ("age", models.IntegerField(verbose_name="Возраст клиента")),
            ],
            managers=[
                ("object_person", django.db.models.manager.Manager()),
            ],
        ),
    ]
